/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UbicacionRouteImport } from './routes/ubicacion'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'

const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeria'
    | '/reservar'
    | '/ubicacion'
    | '/admin/calendario'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/reservar'
    | '/ubicacion'
    | '/admin/calendario'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeria'
    | '/reservar'
    | '/ubicacion'
    | '/admin/calendario'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  ReservarRoute: typeof ReservarRoute
  UbicacionRoute: typeof UbicacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  ReservarRoute: ReservarRoute,
  UbicacionRoute: UbicacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
