/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UbicacionRouteImport } from './routes/ubicacion'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeria': typeof GaleriaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/galeria' | '/reservar' | '/ubicacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/galeria' | '/reservar' | '/ubicacion'
  id: '__root__' | '/' | '/admin' | '/galeria' | '/reservar' | '/ubicacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GaleriaRoute: typeof GaleriaRoute
  ReservarRoute: typeof ReservarRoute
  UbicacionRoute: typeof UbicacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GaleriaRoute: GaleriaRoute,
  ReservarRoute: ReservarRoute,
  UbicacionRoute: UbicacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
