/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as MiReservaRouteImport } from './routes/mi-reserva'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as UbicacionRouteImport } from './routes/ubicacion'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBloqueosRouteImport } from './routes/admin.bloqueos'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminConsultasRouteImport } from './routes/admin.consultas'
import { Route as AdminContenidoRouteImport } from './routes/admin.contenido'
import { Route as AdminGaleriaRouteImport } from './routes/admin.galeria'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLugaresRouteImport } from './routes/admin.lugares'
import { Route as AdminResenasRouteImport } from './routes/admin.resenas'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminTarifasRouteImport } from './routes/admin.tarifas'
import { Route as AdminTemporadasRouteImport } from './routes/admin.temporadas'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReservaRoute = MiReservaRouteImport.update({
  id: '/mi-reserva',
  path: '/mi-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBloqueosRoute = AdminBloqueosRouteImport.update({
  id: '/bloqueos',
  path: '/bloqueos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultasRoute = AdminConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContenidoRoute = AdminContenidoRouteImport.update({
  id: '/contenido',
  path: '/contenido',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriaRoute = AdminGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLugaresRoute = AdminLugaresRouteImport.update({
  id: '/lugares',
  path: '/lugares',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResenasRoute = AdminResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTarifasRoute = AdminTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemporadasRoute = AdminTemporadasRouteImport.update({
  id: '/temporadas',
  path: '/temporadas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/bloqueos': typeof AdminBloqueosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/contenido': typeof AdminContenidoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lugares': typeof AdminLugaresRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/temporadas': typeof AdminTemporadasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/bloqueos': typeof AdminBloqueosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/contenido': typeof AdminContenidoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lugares': typeof AdminLugaresRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/temporadas': typeof AdminTemporadasRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/mi-reserva': typeof MiReservaRoute
  '/reservar': typeof ReservarRoute
  '/ubicacion': typeof UbicacionRoute
  '/admin/bloqueos': typeof AdminBloqueosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/contenido': typeof AdminContenidoRoute
  '/admin/galeria': typeof AdminGaleriaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lugares': typeof AdminLugaresRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/temporadas': typeof AdminTemporadasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeria'
    | '/mi-reserva'
    | '/reservar'
    | '/ubicacion'
    | '/admin/bloqueos'
    | '/admin/calendario'
    | '/admin/configuracion'
    | '/admin/consultas'
    | '/admin/contenido'
    | '/admin/galeria'
    | '/admin/login'
    | '/admin/lugares'
    | '/admin/resenas'
    | '/admin/reservas'
    | '/admin/tarifas'
    | '/admin/temporadas'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/mi-reserva'
    | '/reservar'
    | '/ubicacion'
    | '/admin/bloqueos'
    | '/admin/calendario'
    | '/admin/configuracion'
    | '/admin/consultas'
    | '/admin/contenido'
    | '/admin/galeria'
    | '/admin/login'
    | '/admin/lugares'
    | '/admin/resenas'
    | '/admin/reservas'
    | '/admin/tarifas'
    | '/admin/temporadas'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeria'
    | '/mi-reserva'
    | '/reservar'
    | '/ubicacion'
    | '/admin/bloqueos'
    | '/admin/calendario'
    | '/admin/configuracion'
    | '/admin/consultas'
    | '/admin/contenido'
    | '/admin/galeria'
    | '/admin/login'
    | '/admin/lugares'
    | '/admin/resenas'
    | '/admin/reservas'
    | '/admin/tarifas'
    | '/admin/temporadas'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  MiReservaRoute: typeof MiReservaRoute
  ReservarRoute: typeof ReservarRoute
  UbicacionRoute: typeof UbicacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reserva': {
      id: '/mi-reserva'
      path: '/mi-reserva'
      fullPath: '/mi-reserva'
      preLoaderRoute: typeof MiReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bloqueos': {
      id: '/admin/bloqueos'
      path: '/bloqueos'
      fullPath: '/admin/bloqueos'
      preLoaderRoute: typeof AdminBloqueosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultas': {
      id: '/admin/consultas'
      path: '/consultas'
      fullPath: '/admin/consultas'
      preLoaderRoute: typeof AdminConsultasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contenido': {
      id: '/admin/contenido'
      path: '/contenido'
      fullPath: '/admin/contenido'
      preLoaderRoute: typeof AdminContenidoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeria': {
      id: '/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AdminGaleriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lugares': {
      id: '/admin/lugares'
      path: '/lugares'
      fullPath: '/admin/lugares'
      preLoaderRoute: typeof AdminLugaresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resenas': {
      id: '/admin/resenas'
      path: '/resenas'
      fullPath: '/admin/resenas'
      preLoaderRoute: typeof AdminResenasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tarifas': {
      id: '/admin/tarifas'
      path: '/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AdminTarifasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temporadas': {
      id: '/admin/temporadas'
      path: '/temporadas'
      fullPath: '/admin/temporadas'
      preLoaderRoute: typeof AdminTemporadasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBloqueosRoute: typeof AdminBloqueosRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminConsultasRoute: typeof AdminConsultasRoute
  AdminContenidoRoute: typeof AdminContenidoRoute
  AdminGaleriaRoute: typeof AdminGaleriaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLugaresRoute: typeof AdminLugaresRoute
  AdminResenasRoute: typeof AdminResenasRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminTarifasRoute: typeof AdminTarifasRoute
  AdminTemporadasRoute: typeof AdminTemporadasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIdRoute: typeof AdminClientesIdRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBloqueosRoute: AdminBloqueosRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminConsultasRoute: AdminConsultasRoute,
  AdminContenidoRoute: AdminContenidoRoute,
  AdminGaleriaRoute: AdminGaleriaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLugaresRoute: AdminLugaresRoute,
  AdminResenasRoute: AdminResenasRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminTarifasRoute: AdminTarifasRoute,
  AdminTemporadasRoute: AdminTemporadasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIdRoute: AdminClientesIdRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  MiReservaRoute: MiReservaRoute,
  ReservarRoute: ReservarRoute,
  UbicacionRoute: UbicacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
